//import Vapor

//let team = try [
//    ["name": "Machoke",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
////     "moves": [
////        "Mach Punch",
////        "Bullet Punch",
////        "Submission",
////        "Bulk Up"  ].makeNode(),
//    ].makeNode()
//    ["name": "Garchomp",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
//     "moves": [
//        "Mach Punch",
//        "Bullet Punch",
//        "Submission",
//        "Bulk Up"  ]  ],
//    ["name": "Metagross",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
//     "moves": [
//        "Mach Punch",
//        "Bullet Punch",
//        "Submission",
//        "Bulk Up"  ]  ],
//    ["name": "Muk",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
//     "moves": [
//        "Mach Punch",
//        "Bullet Punch",
//        "Submission",
//        "Bulk Up"  ]  ],
//    ["name": "Gyarados",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
//     "moves": [
//        "Mach Punch",
//        "Bullet Punch",
//        "Submission",
//        "Bulk Up"  ]  ],
//    ["name": "Lurantis",
//     "type": "fighting",
//     "ability": "No Guard",
//     "nature": "Adamant",
//     "gender": "male",
//     "moves": [
//        "Mach Punch",
//        "Bullet Punch",
//        "Submission",
//        "Bulk Up"  ]  ],
//    ].makeNode()
